name: release gem

on:
  release:
    types: [published]

jobs:
  build:
    name: Build + Publish Gem
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    
    - name: Set up ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    
    - name: rspec
      run: |
        gem install rspec
        rspec
    
    - name: build gem
      run: |
        gem build cfn-vpn.gemspec
    
    - name: Publish gem
      uses: dawidd6/action-publish-gem@v1
      with:
        api_key: ${{secrets.RUBYGEMS_API_KEY}}
        github_token: ${{secrets.GITHUB_TOKEN}}